# Generated by Django 4.2 on 2024-10-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='content_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='file',
            field=models.FileField(null=True, upload_to='protected/passwords/attachments/'),
        ),
    ]
