# Generated by Django 4.2 on 2024-10-20 20:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PasswordManager', '0002_password_content_type_alter_password_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='password',
            unique_together={('title', 'user')},
        ),
    ]
