# Generated by Django 4.2 on 2024-12-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feature',
            name='code',
            field=models.CharField(choices=[('number-of-mailbox', 'Number Of Mailbox'), ('storage-gb', 'Storage Gb')], max_length=100, unique=True),
        ),
    ]
