# Generated by Django 4.2 on 2025-01-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_total_size_alter_feature_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
