# Generated by Django 4.2 on 2024-11-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroMail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
