# Generated by Django 4.2 on 2024-09-25 05:16

from django.db import migrations, models
import main.models.mixins.uid


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroMail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAiTemplate',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, main.models.mixins.uid.UIDMixin),
        ),
    ]
