# Generated by Django 4.2 on 2025-01-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroMail', '0002_alter_email_body_alter_email_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailattachment',
            name='file',
        ),
    ]
