# Generated by Django 4.2 on 2025-01-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroMail', '0003_remove_emailattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='s3_url',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
