# Generated by Django 4.2 on 2025-01-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroDrive', '0002_file_is_starred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='s3_url',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sharedaccess',
            name='permission_type',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('full', 'Full')], default='full', max_length=50),
        ),
    ]
