# Generated by Django 4.2 on 2025-01-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NeuroDrive", "0003_remove_file_file_file_s3_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
