# Generated by Django 4.2 on 2025-01-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NeuroDrive", "0004_file_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
