# Generated by Django 4.2 on 2025-01-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NeuroDrive", "0007_alter_file_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="is_removed_metadata",
            field=models.BooleanField(default=False),
        ),
    ]
