# Generated by Django 4.2 on 2025-01-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NeuroDrive", "0008_file_is_removed_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="is_removed_metadata",
        ),
        migrations.AlterField(
            model_name="file",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
